### PR TITLE
Added Unified Native Ad and MediaView Instance.

### PR DESCRIPTION
**Pull request by spilaka**

### CODE REVIEW

**Comment by chauduyphanvu1** [comment]
@spilaka, do you have a test video creative for us to test the MediaView?

**Comment by spilaka** [comment]
Yes, you can test with this "5933fa235e3540d38f308a982b97ddcf".

**Comment by spilaka** [comment]
@chauduyphanvu1  Reviewed the PR. It is working as expected.

**Comment by chauduyphanvu1** [comment]
@spilaka - thanks, we can tell! 😺 However, all PRs go through internal certification + testing before we prepare it & the adapters for release (e.g. code cleanup, changelog, a distributable jar). This PR looks good now, and the release will follow soon!

**Pull request merged**
