### PR TITLE
Updates to OneByAOL (Millennial Media) adapters

### PR DESCRIPTION
**Pull request by nimrich**

### CODE REVIEW

**Comment by rsatrasala** [comment]
Thank you for the PR @nimrich. We are currently evaluating this PR and will push the changes by 03/14

**Comment by nimrich** [comment]
@rsatrasala thanks for keeping me in the loop!  Just let me know if you have any questions or concerns.

**Comment by chauduyphanvu1** [comment]
Thanks, @nimrich! I pushed a commit to the same PR with a few code formatting changes. Other than that, this looks good to be merged soon!

**Comment by nimrich** [comment]
@chauduyphanvu1 sounds good.  Thanks!

**Pull request merged**
