### PR TITLE
Updated AdMob adapter with RequestConfiguration and 18.1.0 Android SDK.

### PR DESCRIPTION
**Pull request by spilaka**
Updated AdMob Adapter to pass CHILD_DIRECT_TREATMENT and UNDER_AGE_CONSENT using RequestConfiguration API.

### CODE REVIEW

**Comment by chauduyphanvu** [comment]
@spilaka, thanks for the PR. Is this work only necessary on Android and not iOS?

**Comment by spilaka** [comment]
@chauduyphanvu  It is for both iOS and Android. iOS PR, will be sent by EOD.

**Comment by chauduyphanvu** [comment]
@spilaka, since your `RequestConfiguration` change has a dependency on v18.1.0, we'll need to hold onto this Pull Request for now because there is no support for AndroidX from MoPub at the moment. It's the same reason why the [last certified version](https://developers.mopub.com/publishers/mediation/integrate/) is at v17.2.1.

**Comment by chauduyphanvu** [comment]
@spilaka, thanks for the PR. We incorporated your changes into https://github.com/mopub/mopub-android-mediation/commit/2c6e740e20462ca11310c56801343e4815abf018!

**Pull request closed without merging**
